from os import path, environ as env

basedir = path.abspath(path.dirname(__file__))
DEBUG = True
ENVIRONMENT=env.get("ENVIRONMENT")
GMAIL_EMAIL_ADDRESS=env.get("GMAIL_EMAIL_ADDRESS")
GMAIL_PASSWORD=env.get("GMAIL_PASSWORD")
HOST="sageleaf.org"
HOSTEDGRAPHITE_APIKEY=env.get("HOSTEDGRAPHITE_APIKEY")
HUMAN_API_BASE_URL='https://user.humanapi.co/v1'
HUMAN_API_CLIENT_APP_KEY=env.get("HUMAN_API_CLIENT_APP_KEY")
HUMAN_API_CLIENT_ID=env.get("HUMAN_API_CLIENT_ID")
HUMAN_API_CLIENT_SECRET=env.get("HUMAN_API_CLIENT_SECRET")
HUMAN_API_PATH_TOKEN='/connect/tokens'
NUTRITIONIX_APP_ID = env.get("NUTRITIONIX_APP_ID")
NUTRITIONIX_APP_KEY = env.get("NUTRITIONIX_APP_KEY")
NUTRITIONIX_BASE_URL = "https://trackapi.nutritionix.com/v2"
NUTRITIONIX_PATH_NUTRIENTS = "/natural/nutrients"
NUTRITIONIX_PATH_SEARCH = "/search/instant"
NUTRITIONIX_PATH_SEARCH_ITEM = "/search/item"
PRIVATE_KEY=env.get("PRIVATE_KEY")
SAGELEAF_EMAIL_ADDRESS=env.get("SAGELEAF_EMAIL_ADDRESS")
SQLALCHEMY_DATABASE_URI=env.get("DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_ECHO = False
TESTING = True